# Generated by Django 2.0.3 on 2018-03-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(default=10000)),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=12)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('account_type', models.CharField(choices=[('ss', 'store superuser'), ('sc', 'store cook'), ('dm', 'delivery man'), ('fc', 'food customer')], max_length=2)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
